import { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, StringSelectMenuBuilder, PermissionFlagsBits, MessageFlags, ChannelType } from 'discord.js';
import { createTicket } from '../../../services/ticket.js';
import { getP2PConfig, getP2PPaymentConfig, buildBuyPaymentEmbed, buildSellPaymentEmbed } from '../../../services/p2pService.js';
import { logger } from '../../../utils/logger.js';
import { errorEmbed } from '../../../utils/embeds.js';
import { wizardSelections, buildWizardComponents } from '../../selectMenus/p2p/p2pWizardSelect.js';

function safeGetField(fields, ...keys) {
    if (!fields) return null;
    for (const key of keys) {
        try {
            const val = fields.getTextInputValue(key);
            if (val) return val;
        } catch (_) {
            // Ignore missing field errors
        }
    }
    return null;
}

// ==================== STEP 2: Amount Modal Submit → Show Dropdowns ====================

export const p2pAmountModalHandler = {
    name: 'p2p_amount_modal',
    async execute(interaction, client, args) {
        const tradeType = args[0] || 'buy';
        const kycType = args[1] || 'kyc';
        const isBuy = tradeType === 'buy';
        const isKyc = kycType === 'kyc';

        const amount = safeGetField(interaction.fields, 'q1_amount') || '100';

        // Store amount in wizard selections
        const key = `${interaction.guildId}:${interaction.user.id}`;
        wizardSelections.set(key, {
            tradeType,
            kycType,
            amount,
        });

        // Build ephemeral message with dropdowns
        const embed = new EmbedBuilder()
            .setTitle(`${isBuy ? '🛒 Buy' : '🔴 Sell'} ${amount} USDT — Select Options`)
            .setDescription(
                `**Amount:** \`${amount} USDT\` ✅\n\n` +
                `Now select your options below:\n\n` +
                `> 1️⃣ Choose your **${isBuy ? 'Payment' : 'Payout'} Method**\n` +
                `> 2️⃣ Choose your **Crypto Network**\n` +
                `> 3️⃣ Click **Next** to enter ${isBuy ? 'wallet address' : 'payout details'}\n\n` +
                `*${isKyc ? '🔒 KYC Verified Trade' : '⚡ Non-KYC Quick Trade'}*`
            )
            .setColor(isBuy ? '#2ECC71' : '#E74C3C')
            .setFooter({ text: 'Vanta P2P • Select both options then click Next' });

        // Next + Cancel buttons and menus generated by builder helper
        const updatedComponents = buildWizardComponents(tradeType, kycType);

        await interaction.reply({
            embeds: [embed],
            components: updatedComponents,
            flags: MessageFlags.Ephemeral,
        });
    }
};

// ==================== FINAL STEP: Details Modal Submit → Create Ticket ====================

export const p2pDetailsModalHandler = {
    name: 'p2p_details_modal',
    async execute(interaction, client, args) {
        await interaction.deferReply({ flags: MessageFlags.Ephemeral });

        try {
            const tradeType = args[0] || 'buy';
            const kycType = args[1] || 'kyc';
            const isBuy = tradeType === 'buy';
            const isKyc = kycType === 'kyc';

            // Get stored wizard selections
            const key = `${interaction.guildId}:${interaction.user.id}`;
            const selections = wizardSelections.get(key) || {};

            const amountDisplay = selections.amount || '100';
            const paymentMethod = (selections.paymentMethod || 'UPI').toUpperCase();
            const networkRaw = selections.network || 'USDT_TRC20';
            const networkLabel = networkRaw.replace(/_/g, ' ').toUpperCase();

            let addressDisplay = 'N/A';
            if (isBuy) {
                addressDisplay = safeGetField(interaction.fields, 'q_address') || 'N/A';
            } else {
                addressDisplay = safeGetField(interaction.fields, 'q_details') || 'N/A';
            }

            // Clean up wizard selections
            wizardSelections.delete(key);

            const config = await getP2PConfig(interaction.guildId);
            const paymentConfig = await getP2PPaymentConfig(interaction.guildId);

            const reason = `${isBuy ? 'Buy' : 'Sell'} ${amountDisplay} USDT via ${paymentMethod} (${networkLabel})`;

            // Dynamically detect marketplace category
            const marketCategory = interaction.guild.channels.cache.find(c => 
                c.type === ChannelType.GuildCategory && 
                (c.name.toLowerCase().includes('market place') || 
                 c.name.toLowerCase().includes('marketplace') || 
                 c.name.toLowerCase().includes('p2p'))
            );
            const targetCategoryId = marketCategory ? marketCategory.id : null;

            // 1. Create Private Ticket Channel
            const result = await createTicket(
                interaction.guild,
                interaction.member,
                targetCategoryId,
                reason,
                'none'
            );

            const ticketChannel = result.channel;

            // 2. Strict Permissions Setup
            const staffRoleId = config.staffRoleId;
            const permissionOverlays = [
                {
                    id: interaction.guild.roles.everyone.id,
                    deny: [PermissionFlagsBits.ViewChannel]
                },
                {
                    id: interaction.user.id,
                    allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks, PermissionFlagsBits.AttachFiles]
                },
                {
                    id: interaction.client.user.id,
                    allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks, PermissionFlagsBits.AttachFiles]
                }
            ];

            if (staffRoleId && interaction.guild.roles.cache.has(staffRoleId)) {
                permissionOverlays.push({
                    id: staffRoleId,
                    allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks, PermissionFlagsBits.AttachFiles]
                });
            }

            await ticketChannel.permissionOverwrites.set(permissionOverlays).catch(() => null);

            // 3. Build Ticket Welcome Summary Card
            const title = isBuy
                ? `🛒 Buy USDT Trade Request (${isKyc ? 'KYC Verified' : 'Non-KYC'})`
                : `🔴 Sell USDT Trade Request (${isKyc ? 'KYC Verified' : 'Non-KYC'})`;

            const verificationTag = isKyc ? 'KYC Verified Deal' : 'Non-KYC Deal';
            let cardDescription = '';

            if (isBuy) {
                cardDescription = [
                    `Welcome <@${interaction.user.id}>! A verified Middleman / Support staff will assist your trade shortly.\n`,
                    `> **Trader / Creator:** \`${interaction.user.id}\``,
                    `> **Trade Direction:** \`BUY USDT\``,
                    `> **1. Requested Amount:** \`${amountDisplay} USDT\``,
                    `> **2. Payment Method:** \`${paymentMethod}\``,
                    `> **3. Crypto Network:** \`${networkLabel}\``,
                    `> **4. Your Receiving Wallet Address:** \`${addressDisplay}\``,
                    `> **Verification:** \`${verificationTag}\``,
                    `> **Security:** \`Auto-MM Protected Trade\``
                ].join('\n');
            } else {
                cardDescription = [
                    `Welcome <@${interaction.user.id}>! A verified Middleman / Support staff will assist your trade shortly.\n`,
                    `> **Trader / Creator:** \`${interaction.user.id}\``,
                    `> **Trade Direction:** \`SELL USDT\``,
                    `> **1. Requested Amount:** \`${amountDisplay} USDT\``,
                    `> **2. Payout Method:** \`${paymentMethod}\``,
                    `> **3. Payout Details (${paymentMethod}):** \`${addressDisplay}\``,
                    `> **4. Deposit Crypto Network:** \`${networkLabel}\``,
                    `> **Verification:** \`${verificationTag}\``,
                    `> **Security:** \`Auto-MM Protected Trade\``
                ].join('\n');
            }

            const summaryEmbed = new EmbedBuilder()
                .setTitle(title)
                .setDescription(cardDescription)
                .setColor(isBuy ? '#2ECC71' : '#E74C3C')
                .setFooter({ text: 'Vanta P2P Trade System • Keep all trade chats inside this channel' });

            const controlsRow = new ActionRowBuilder().addComponents(
                new ButtonBuilder()
                    .setCustomId('p2p_autolog_ticket_btn')
                    .setLabel('⚡ Auto-Log Deal Proof')
                    .setStyle(ButtonStyle.Success),
                new ButtonBuilder()
                    .setCustomId('ticket_close')
                    .setLabel('🔒 Close Ticket')
                    .setStyle(ButtonStyle.Danger)
            );

            await ticketChannel.send({
                content: `<@${interaction.user.id}> ${staffRoleId ? `<@&${staffRoleId}>` : ''}`,
                embeds: [summaryEmbed],
                components: [controlsRow]
            });

            // 4. Auto-dispatch Payment QR Code / Bank Details or Deposit Wallet
            if (isBuy) {
                const paymentEmbed = buildBuyPaymentEmbed(paymentMethod, paymentConfig);
                await ticketChannel.send({ embeds: [paymentEmbed] });
            } else {
                const depositEmbed = buildSellPaymentEmbed(networkLabel, paymentConfig);
                await ticketChannel.send({ embeds: [depositEmbed] });
            }

            await interaction.editReply({
                content: `✅ Your **${isBuy ? 'Buy' : 'Sell'} USDT Ticket** has been created in <#${ticketChannel.id}>!`
            });

        } catch (err) {
            logger.error('Failed to create ticket from wizard:', err);
            const userMsg = err.userMessage || err.message || 'Failed to create ticket channel.';
            await interaction.editReply({
                embeds: [errorEmbed('Ticket Creation Notice', userMsg)]
            }).catch(() => null);
        }
    }
};

export default [
    p2pAmountModalHandler,
    p2pDetailsModalHandler,
];
